server:
  port: 8888
  servlet:
    encoding:
      charset: 'UTF-8'
      enabled: true
      force: true

logging:
  level:
    org.springframework.boot.context.event: warn

profile:
  nakji:
    imgUrl: 'https://avatars.githubusercontent.com/u/37291245?v=4'
    srcUrl: '/nakji/'
    NAVER_ID: 'DXUdYJLVPWaC2kxD_PUm'
    NAVER_KEY: 'SFvAihes1e'
    GOOGLE_KEY: 'AIzaSyBxdEGZKno9zIewJzFjMzCqngx_dxuWdHE'
    GOOGLE_CX: 'c7afc5a33141f45f6'
    GOOGLE_CLIENT_ID: '895857791329-mi3g48445im7h7o1lceoslcef0vgg30u.apps.googleusercontent.com'
    GOOGLE_CLIENT_SECRET: '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'
