server:
  port: 3000

  servlet:
    encoding:
      charset: 'UTF-8'
      enabled: true
      force: true

logging:
  level:
    org:
      springframework:
        web: DEBUG
        boot.context.event: warn

spring:
  config:
    import:
      - 'classpath:db.yml'
      - 'classpath:third-party.yml'
      - 'classpath:security.yml'