logging:
  level:
    org.springframework.boot.context.event: warn

profile:
  nakji:
    imgUrl: 'https://avatars.githubusercontent.com/u/37291245?v=4'
    srcUrl: '/nakji/'

  zangji:
    imgUrl: 'https://github.com/jihoon-jang'
    srcUrl: '/zangji/'


