# This is a basic workflow to help you get started with Actions

name: Workflow Nakji

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master", "nakji" ]
  pull_request:
    branches: [ "master", "nakji" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  set_env_variables:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      NAKJI_NAVER_ID: ${{ secrets.NAKJI_NAVER_ID }}
      NAKJI_NAVER_KEY: ${{ secrets.NAKJI_NAVER_KEY }}
      NAKJI_GOOGLE_KEY: ${{ secrets.NAKJI_GOOGLE_KEY }}
      NAKJI_GOOGLE_CX: ${{ secrets.NAKJI_GOOGLE_CX }}
